#!/bin/bash

brew install fish
brew install vim
brew install stow
brew install tmux
brew install reattach-to-user-namespace
brew install ctags --HEAD
brew install hg
brew install lighttpd
brew install wget
brew install htop
brew install wine
brew install sloccount
brew install datamash
brew install lua
brew install python
brew install postgresql
brew install pngcrush
brew install mutt
brew install urlview
brew install contacts
brew install tty-clock
brew install cmus
brew install youtube-dl
brew install homebrew/games/nethack
brew install tree
brew install jq
brew install apache-spark
brew install auto-scaling
brew install aws-cfn-tools
brew install aws-elasticache
brew install aws-elasticbeanstalk
brew install aws-sns-cli
brew install awscli
brew install bfg
brew install boost
brew install boot2docker
brew install bowery
brew install c-ares
brew install cloud-watch
brew install cmatrix
brew install cscope
brew install curl
brew install dnsmasq
brew install docker
brew install docker-compose
brew install docker-machine
brew install docker-swarm
brew install ec2-ami-tools
brew install ec2-api-tools
brew install elasticsearch
brew install elb-tools
brew install emacs
brew install fig
brew install fish
brew install fortune
brew install fping
brew install freetype
brew install gdbm
brew install gettext
brew install glib
brew install gmp
brew install gnupg
brew install gnutls
brew install go
brew install gradle
brew install graphviz
brew install h2
brew install hadoop
#brew install htop-osx
brew install iftop
brew install imagemagick
brew install iperf3
brew install irssi
brew install jpeg
brew install jq
brew install kafka
brew install kafkacat
brew install keybase
brew install keychain
brew install libevent
brew install libffi
brew install libpng
brew install librdkafka
brew install libtasn1
brew install libtiff
brew install libtool
brew install libwebsockets
brew install libyaml
brew install logstash
brew install lynx
brew install lzlib
brew install macvim
brew install maven
brew install mercurial
brew install mobile-shell
brew install mongodb
brew install mosquitto
brew install mtr
brew install mysql
brew install nettle
brew install ngrep
brew install nmap
brew install node
brew install oniguruma
brew install openssl
brew install ossp-uuid
brew install packer
brew install pcre
brew install pixman
brew install pkg-config
brew install play
brew install postgresql
brew install protobuf
brew install pwgen
brew install qemu
brew install rds-command-line-tools
brew install readline
brew install reattach-to-user-namespace
brew install redis
brew install redshift
brew install ruby21
brew install s3cmd
brew install sbt
brew install scala
brew install siege
brew install sl
brew install snappy
brew install sntop
brew install spark
brew install sqlite
brew install stow
brew install terraform
brew install tmux
brew install tree
brew install varnish
brew install watch
brew install wget
brew install wrk
brew install xz
brew install zookeeper
brew install zsh
