#!/bin/bash
# These are my current packages. To get yours:
# brew list | awk '{sub(/^/, "brew install ")};1'
# This will generate a list of packages that you can paste in here.
brew install apache-spark
brew install auto-scaling
brew install autoconf
brew install aws-cfn-tools
brew install aws-elasticache
brew install aws-elasticbeanstalk
brew install aws-sns-cli
brew install awscli
brew install bfg
brew install boost
brew install boot2docker
brew install bowery
brew install c-ares
brew install cask
brew install cloud-watch
brew install cmatrix
brew install cmus
brew install contacts
brew install cscope
brew install ctags
brew install curl
brew install dnsmasq
brew install docker
brew install docker-compose
brew install docker-machine
brew install docker-swarm
brew install ec2-ami-tools
brew install ec2-api-tools
brew install elasticsearch
brew install elb-tools
brew install emacs
brew install faad2
brew install fig
brew install fish
brew install flac
brew install fortune
brew install fping
brew install freetype
brew install gdbm
brew install gettext
brew install git-crypt
brew install glib
brew install gmp
brew install gnupg
brew install gnutls
brew install go
brew install gradle
brew install graphviz
brew install h2
brew install hadoop
brew install htop-osx
brew install icu4c
brew install iftop
brew install imagemagick
brew install iperf3
brew install irssi
brew install jpeg
brew install jq
brew install kafka
brew install kafkacat
brew install keychain
brew install libao
brew install libcue
brew install libevent
brew install libffi
brew install libogg
brew install libpng
brew install librdkafka
brew install libtasn1
brew install libtiff
brew install libtool
brew install libvorbis
brew install libwebsockets
brew install libxml2
brew install libyaml
brew install lighttpd
brew install logstash
brew install lua
brew install lynx
brew install lzlib
brew install macvim
brew install mad
brew install maven
brew install md5sha1sum
brew install mercurial
brew install mobile-shell
brew install mongodb
brew install mosquitto
brew install mp4v2
brew install mtr
brew install mutt
brew install mysql
brew install ncdu
brew install nethack
brew install nettle
brew install nginx
brew install ngrep
brew install nmap
brew install node
brew install oniguruma
brew install openssl
brew install ossp-uuid
brew install packer
brew install pcre
brew install pcre2
brew install perl
brew install php-code-sniffer
brew install php71
brew install pixman
brew install pkg-config
brew install play
brew install pngcrush
brew install postgresql
brew install protobuf
brew install pwgen
brew install python
brew install qemu
brew install rds-command-line-tools
brew install readline
brew install reattach-to-user-namespace
brew install redis
brew install redshift
brew install rhino
brew install ruby
brew install ruby21
brew install s3cmd
brew install sbt
brew install scala
brew install scons
brew install siege
brew install sl
brew install sloccount
brew install snappy
brew install sntop
brew install spark
brew install sqlite
brew install stow
brew install terraform
brew install tmux
brew install tokyo-cabinet
brew install tree
brew install tty-clock
brew install unixodbc
brew install urlview
brew install varnish
brew install vim
brew install watch
brew install wget
brew install wrk
brew install xz
brew install youtube-dl
brew install zookeeper
brew install zsh
